# Generated by Django 5.2 on 2025-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('icon', models.URLField(blank=True, help_text='URL to the notification icon', null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL to redirect on notification click', null=True)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('time_to_live', models.PositiveIntegerField(blank=True, default=3600, help_text='Time in seconds for notification to live')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
