# Generated by Django 5.2 on 2025-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='home_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'All'), ('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('sports', 'Sports'), ('formal', 'Formal'), ('gadgets', 'Gadgets'), ('clothing', 'Clothing'), ('fashion', 'Fashion'), ('electronics', 'electronics'), ('stationeries', 'Stationeries'), ('gender_gadgets', 'Gender_gadgets'), ('kitchenware', 'Kitchenware'), ('home_items', 'Home items'), ('featured', 'Featured'), ('games', 'Games'), ('books', 'Books'), ('accessories', 'Accessories'), ('handbags', 'Handbags'), ('oils', 'Oils'), ('other', 'other')], default='all', max_length=20),
        ),
    ]
