# Generated by Django 5.2 on 2025-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_remove_product_home_category_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rates',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating from 0.0 to 5.0', max_digits=3),
        ),
    ]
