# Generated by Django 5.2 on 2025-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_product_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unitTag',
            field=models.SlugField(default='23000', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
