# Generated by Django 5.2 on 2025-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_product_unittag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitTag',
            field=models.SlugField(blank=True, editable=False, max_length=100),
        ),
    ]
