# Generated by Django 5.2 on 2025-04-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_alter_product_unittag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids'), ('Sports', 'Sports'), ('Formal', 'Formal'), ('Gadgets', 'Gadgets'), ('Clothing', 'Clothing'), ('Fashion', 'Fashion'), ('Electronics', 'electronics'), ('Stationeries', 'Stationeries'), ('Gender_gadgets', 'Gender_gadgets'), ('Kitchenware', 'Kitchenware'), ('Home_items', 'Home items'), ('Featured', 'Featured'), ('Games', 'Games'), ('Books', 'Books'), ('Accessories', 'Accessories'), ('Handbags', 'Handbags'), ('Oils', 'Oils'), ('Other', 'Other')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='cloth_category',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Men_clothing', 'Men Clothing'), ('Women_clothing', 'Women Clothing'), ('Kids_clothing', 'Kids Clothing'), ('Sports_activewear', 'Sports & Activewear'), ('Formal_workwear', 'Formal & Workwear'), ('Gadgets', 'Gadgets')], default='empty', max_length=20),
        ),
    ]
