# Generated by Django 5.2 on 2025-04-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_alter_product_category_alter_product_cloth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitTag',
            field=models.SlugField(blank=True, default=0, editable=False, max_length=100),
        ),
    ]
