# Generated by Django 5.2 on 2025-04-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0008_alter_product_unittag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unitTag',
            field=models.SlugField(blank=True, default=0, max_length=100),
        ),
    ]
