# Generated by Django 5.2 on 2025-04-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0010_alter_product_description_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Women', 'Women'), ('Men', 'Men'), ('Kids', 'Kids'), ('Sports', 'Sports'), ('Formal', 'Formal'), ('Gadgets', 'Gadgets'), ('Clothing', 'Clothing'), ('Fashion', 'Fashion'), ('Electronics', 'electronics'), ('Stationeries', 'Stationeries'), ('Gender_gadgets', 'Gender_gadgets'), ('Kitchenware', 'Kitchenware'), ('Home_items', 'Home items'), ('Featured', 'Featured'), ('Games', 'Games'), ('Books', 'Books'), ('Accessories', 'Accessories'), ('Handbags', 'Handbags'), ('Discount', 'Discount'), ('Other', 'Other')], default='all', max_length=20),
        ),
    ]
