# Generated by Django 5.2 on 2025-06-05 15:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Brown', 'Brown'), ('Black', 'Black'), ('White', 'White'), ('Gray', 'Gray'), ('Cyan', 'Cyan'), ('Magenta', 'Magenta'), ('Navy', 'Navy'), ('Teal', 'Teal'), ('Maroon', 'Maroon'), ('Lime', 'Lime'), ('Olive', 'Olive'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=100),
        ),
    ]
